# Generated by Django 3.2.20 on 2023-07-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_recipe_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
